version: '3.7'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_MYSQL_DATABASE}
      MYSQL_USER: ${DATABASE_MYSQL_USER}
      MYSQL_PASSWORD: ${DATABASE_MYSQL_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
